sudo: required
services: 
  - docker

before_install:
  - docker build -t liondancer/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true liondancer/docker-react npm run test -- --coverage